### ISSUE TITLE
Make outputs consumable via REST api

### ISSUE THREAD

**Issue by cburgdorf** [machinelabs/feature-votes#2]
### Feature request

Once https://github.com/machinelabs/feature-votes/issues/1 lands, it would be great to not only be able to download those outputs but also be able to consume them via REST API.

### Use cases

- create labs that consume pre-trained models from other labs/executions
- create applications that consume assets from other labs/executions

**Comment by 0x-r4bbit** [comment]
This has landed! https://blog.machinelabs.ai/2017/10/16/new-rest-api-and-folder-support/
