### ISSUE TITLE
Create documentation and guides

### ISSUE THREAD

**Issue by cburgdorf** [machinelabs/feature-votes#3]
As a user I'd like to read guides and documentation about how to use MachineLabs.

**Comment by jlooper** [comment]
Same here! I'm going to try to flip one of the Google Codelabs into Machinelabs, and that pattern might be reproducible as a tutorial/demo

**Comment by cburgdorf** [comment]
>I'm going to try to flip one of the Google Codelabs into Machinelabs

That sounds awesome. Is there anything we can already take a look at? Docs and guides will also be open source so we will welcome any contributions there!

**Comment by jlooper** [comment]
hi, I have forked the Google Codelabs code base and am using it for NativeScript SnackLabs (https://github.com/jlooper/snacklabs) - they end up looking like this: https://jlooper.github.io/snacklabs/snacklabs/flexbox/#0

I modeled them after this great lab: https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#0 which really helped onboard me to TensorFlow. I was hoping to take that codelab and see if the image classification example would run on Machinelabs.

**Comment by 0x-r4bbit** [comment]
@jlooper are you still experimenting with this?

BTW: I'll close this one as https://docs.machinelabs.ai landed.

I propose we open new issues for specific docs requests like "Style Transfer Tutorial" or something.

**Comment by jlooper** [comment]
@PascalPrecht I'm going to dig into your docs now! Thanks for this project, sorry to be 'in 'n' out' :) - observing!

**Comment by 0x-r4bbit** [comment]
No worries @jlooper ! We appreciate any time you put into using ML and also any feedback we can get.

Let us know if you miss anything so we can fix it!
