### ISSUE TITLE
Support downloads via ml.yaml

### ISSUE THREAD

**Issue by cburgdorf** [machinelabs/feature-votes#6]
### Feature request

As a user I'd like to be able to name downloads in the `ml.yaml` so they become available in my execution in a special directory.

This can already be done using bare Python (e.g `os.system('curl -O http://some.thing.zi')` but it's not the most ergonomic thing to do.

### Use cases

- Make downloads more ergonomic

**Comment by 0x-r4bbit** [comment]
This landed :)
